### ISSUE TITLE
Weird Error in Handlers.js

### ISSUE THREAD

**Issue by learn2mine** [learn2mine/pirple-section-3#1]
Whenever I run `node index.js` it always says this...
```
/home/tristan/node-course/pirple-section-3/lib/handlers.js:370
});
 ^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/tristan/node-course/pirple-section-3/index.js:13:16)
```
Keep in mind that the actual handlers.js file is not even 370 lines long...

**Comment by learn2mine** [comment]
Fixed
